#!/usr/bin/env bash
# Создает файл конфигурации SSH для отключения логина по паролю и root
# MODULE_ORDER: 26
# MODULE_TYPE: modifyq
# MODULE_NAME: module.permissions.modify.name

set -Eeuo pipefail

readonly PROJECT_ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd)/.."

source "${PROJECT_ROOT}/lib/vars.conf"
source "${PROJECT_ROOT}/lib/logging.sh"
source "${PROJECT_ROOT}/lib/i18n/loader.sh"
source "${PROJECT_ROOT}/lib/user_confirmation.sh"
source "${PROJECT_ROOT}/modules/helpers/common.sh"
source "${PROJECT_ROOT}/modules/helpers/permissions-helpers.sh"

trap log_stop EXIT

# @type:        Orchestrator
# @description: Создает файл конфигурации SSH с настройками доступа
#               Отключает логин root и по паролю, включает вход по ключам
# @stdin:       нет
# @stdout:      нет
# @exit_code:   0 - успешно
#               1 - ошибка создания файла
permissions::ssh::create_permissions_config() {
    local last_prefix new_prefix config_file_path

    last_prefix=$(permissions::ssh::find_last_prefix)

    if [[ -z "$last_prefix" ]]; then
        new_prefix="10"
        log_info "Файлы с настройками не найдены, используется префикс: $new_prefix"
    else
        log_info "Найден последний префикс: $last_prefix"
        new_prefix=$(( last_prefix + 10 ))
    fi

    config_file_path="${SSH_CONFIGD_DIR}/${new_prefix}${BSSS_PERMISSIONS_CONFIG_FILE_NAME}"

    log_info "Создание файла конфигурации: $config_file_path"

    {
        printf '%s\n' "# Generated by ${UTIL_NAME^^}"
        printf '%s\n' "PermitRootLogin no"
        printf '%s\n' "PasswordAuthentication no"
        printf '%s\n' "PubkeyAuthentication yes"
    } > "$config_file_path" || return 1

    log_info "Файл создан"
}

# @type:        Orchestrator
# @description: Проверяет условия и создает файл конфигурации при выполнении
# @stdin:       нет
# @stdout:      нет
# @exit_code:   0 - успешно
#               2 - отмена пользователем или несоответствие условий
permissions::orchestrator::apply() {
    local current_conn_type root_id auth_id

    current_conn_type=$(permissions::auth::get_method | tr -d '\0')

    if [[ "$current_conn_type" != "PUBLICKEY" ]]; then
        log_warn "Подключитесь по SSH ключу пользователем отличным от root"
        return 2
    fi

    root_id=$(id -u root)
    auth_id=$(id -u "$(logname)")

    if (( root_id == auth_id )); then
        log_warn "Нельзя отключать PermitRootLogin и PasswordAuthentication"
        log_warn "Подключитесь по SSH ключу пользователем отличным от root"
        return 2
    fi

    log_info "Можно отключать PermitRootLogin и PasswordAuthentication"

    if io::confirm_action "Отключить?"; then
        permissions::ssh::create_permissions_config
    fi
}

# @type:        Orchestrator
# @description: Основная точка входа для модуля создания прав доступа
# @params:      нет
# @stdin:       нет
# @stdout:      нет
# @exit_code:   0 - успешно
#               2 - отмена пользователем или несоответствие условий
main() {
    i18n::load
    log_start
    io::confirm_action "Запустить модуль?"
    permissions::orchestrator::apply
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
