#!/usr/bin/env bash
# Изменяет SSH порт
# MODULE_TYPE: modify

set -Eeuo pipefail

readonly MAIN_DIR_PATH="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd)"
readonly CURRENT_MODULE_NAME="$(basename "$0")"

source "${MAIN_DIR_PATH}/lib/vars.conf"
source "${MAIN_DIR_PATH}/lib/logging.sh"
source "${MAIN_DIR_PATH}/lib/user_confirmation.sh"
source "${MAIN_DIR_PATH}/modules/common-helpers.sh"

ufw_add_bsss_rule() {
    local port
    while read -r -d '' port; do
        if ufw allow "${port}"/tcp comment 'Generated by BSSS' >> err.log 2>&1; then
            log_info "Успешно: ufw allow "${port}"/tcp comment 'Generated by BSSS'"
        else
            log_info "Ошибка: ufw allow "${port}"/tcp comment 'Generated by BSSS'"
        fi
    done
 
}

printf '%s\0' "24" | ufw_add_bsss_rule
