#!/usr/bin/env bash
# Изменяет SSH порт
# MODULE_TYPE: modify

set -Eeuo pipefail

readonly MAIN_DIR_PATH="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd)"
readonly CURRENT_MODULE_NAME="$(basename "$0")"

source "${MAIN_DIR_PATH}/lib/vars.conf"
source "${MAIN_DIR_PATH}/lib/logging.sh"
source "${MAIN_DIR_PATH}/lib/user_confirmation.sh"
source "${MAIN_DIR_PATH}/modules/common-helpers.sh"

ufw_remove_managed_rules() {
    local found_any=0
    local rule_args
    
    while IFS= read -r -d '' rule_args; do
        found_any=1

        if printf '%s' "$rule_args" | xargs ufw --force delete >>err.log 2>&1; then
            log_info "Успешно: ufw --force delete $rule_args"
        else
            log_error "Ошибка: ufw --force delete $rule_args"
        fi
    done < <(
        ufw show added \
        | awk -v marker="^ufw.*comment[[:space:]]+\x27Generated by ${UTIL_NAME^^}\x27" '
            BEGIN { ORS="\0" }
            $0 ~ marker {
                sub(/^ufw[[:space:]]+/, "");
                print $0;
            }
        '
    )

    if (( found_any == 0 )); then
        log_info "Активных правил для ${UTIL_NAME^^} не обнаружено."
    fi
}

ufw_remove_managed_rules
