#!/usr/bin/env bash
# Изменяет SSH порт
# MODULE_TYPE: modify

set -Eeuo pipefail

readonly MAIN_DIR_PATH="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd)"
readonly CURRENT_MODULE_NAME="$(basename "$0")"

source "${MAIN_DIR_PATH}/lib/vars.conf"
source "${MAIN_DIR_PATH}/lib/logging.sh"
source "${MAIN_DIR_PATH}/lib/user_confirmation.sh"
source "${MAIN_DIR_PATH}/modules/common-helpers.sh"

ufw_remove_managed_rules() {
    # log_info "Очистка старых правил UFW..."

    # Поток: 
    # 1. Берем список всех добавленных правил
    # 2. Ищем наш маркер (BSSS)
    # 3. Заменяем 'allow' или 'deny' на 'delete'
    # 4. Выполняем через xargs
    
    # ufw show added \
    # | grep "Generated by ${UTIL_NAME^^}" \
    # | sed -E 's/^ufw\s(.*)$/ufw --force delete \1 /' \
    # | xargs -r -d '\n' sh -c
    
    # log_success "Старые правила очищены."
    # Собираем список команд на удаление в переменную
    local rules_for_delete
    rules_for_delete=$(ufw show added | grep "Generated by ${UTIL_NAME^^}" | sed -E 's/^ufw\s+(.+)\s+comment\s+.*$/\1/' || true)

    if [ -n "$rules_for_delete" ]; then
        # Используем while для корректной обработки строк
        printf '%s\n' "$rules_for_delete" | while read -r rule; do
            ufw --force delete $rule
        done
    else
        log_info "Активных правил для ${UTIL_NAME} не найдено."
    fi
}

ufw_remove_managed_rules